name: chaleno
description: A package to web scraping data from websites easily and faster using less code lines.
version: 0.0.7
homepage: https://github.com/Movinghead333/chaleno

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  http: ">=1.2.0 <2.0.0"
  html: ">=0.15.4 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter